// <auto-generated />
using System;
using InterkontinentalAPI.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterkontinentalAPI.Migrations
{
    [DbContext(typeof(InterkontinentalContext))]
    [Migration("20221112212042_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InterkontinentalAPI.Entities.Counter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("GameId");

                    b.ToTable("Counters");
                });

            modelBuilder.Entity("InterkontinentalAPI.Entities.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Praga"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kompostownik"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kolin"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kutna Hora"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Szansa 1"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kolej Europejska"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Prypeć"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Gazownia"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Kijów"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Odwiedzanie Gułagu"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Odessa"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Watykan"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Lotnisko"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Płaza"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Balin"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Regulice"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Szansa 2"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Kolej Transsyberyjska"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Zaginiona Wioska"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Berlin Wschodni"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Drezno"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Zwickau"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Koksownia"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Władywostok"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Partyjna Działka"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Jekaterynburg"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Nowosybirsk"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Bogota"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Szansa 3"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Kolej Światowa"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Hawana"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Grill"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Meksyk"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Sydney"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Gułag"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Melbourne"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Wellington"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Zanzibar"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Port"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Dakar"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Kair"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Singapur"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Szansa 4"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Kolej Towarowa"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Tajwan"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Truskawki"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Sosnowiec"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Kopalnia Uranu"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Bukareszt"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Start"
                        });
                });

            modelBuilder.Entity("InterkontinentalAPI.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("InterkontinentalAPI.Entities.Counter", b =>
                {
                    b.HasOne("InterkontinentalAPI.Entities.Field", "Field")
                        .WithMany("Counters")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterkontinentalAPI.Entities.Game", "Game")
                        .WithMany("Counters")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("InterkontinentalAPI.Entities.Field", b =>
                {
                    b.Navigation("Counters");
                });

            modelBuilder.Entity("InterkontinentalAPI.Entities.Game", b =>
                {
                    b.Navigation("Counters");
                });
#pragma warning restore 612, 618
        }
    }
}
